skillMetadata:
  sections:
    - name: Configuration
      fields:
        - name: url
          type: text
          label: MagicMirror URL
          value: "http://localhost:8080"
        - name: key
          type: password
          label: MagicMirror API key
          value: ""
        - name: verify
          type: checkbox
          label: Verify SSL certificate
          value: "false"
